// Generated by CoffeeScript 1.6.3
var AUTOMATOR_HIDE_DEBUG, Automator, automator_log;

AUTOMATOR_HIDE_DEBUG = true;

automator_log = function(message) {
  if (!AUTOMATOR_HIDE_DEBUG) {
    return console.log(message);
  }
};

Automator = (function() {
  Automator.prototype.options = {
    namespace: "automator"
  };

  function Automator(datastore, options) {
    if (options == null) {
      options = {};
    }
    $.extend(this.options, options);
    this.datastore = datastore;
    this.categories = datastore.getTable("" + this.options.namespace + "-categories");
    this.words = datastore.getTable("" + this.options.namespace + "-words");
  }

  Automator.prototyp