// Generated by CoffeeScript 1.6.3
var AUTOMATOR_HIDE_DEBUG, Automator, automator_log;

AUTOMATOR_HIDE_DEBUG = true;

automator_log = function(message) {
  if (!AUTOMATOR_HIDE_DEBUG) {
    return console.log(message);
  }
};

Automator = (function() {
  Automator.prototype.options = {
    namespace: "automator"
  };

  function Automator(datastor